### ISSUE TITLE
Typescript bindings

### ISSUE THREAD

**Issue by GeoffMcLennan** [stoefln/node-native-ocr#11]
Hi! Thanks for making this library, this looks very promising compared to competing OCR libraries for Javascript.

However, I am trying to include this in my Typescript project, but since this library does not seem to have Typescript type declarations I'm getting some issues. If you do have the .d.ts files somewhere and I'm just missing them let me know!

I'll look into creating some custom declarations for my project, but it would be great if this library included them by default for future Typescript consumers. If its any help, I can provide my custom declarations once I complete them

**Comment by stoefln** [comment]
Hi @GeoffMcLennan I don't have any TS declarations, but it would be amazing if you could contribute them!

**Comment by GeoffMcLennan** [comment]
@stoefln Sounds good! I'll generate some manually, but that means if the base API of any exported members from this library change, they will be out of date. I don't have any experience with maintaining a library like this, but I would bet there's some CI tool that we could add to automate generation of TS declarations in the future. I'll keep an eye out for that as well

**Comment by GeoffMcLennan** [comment]
Created a PR with manually defined declarations: https://github.com/stoefln/node-native-ocr/pull/12/files
